sudo: required
services:
  - docker

before_install:
  - docker build -t bhavyamarapa/radio-button-app  -f Dockerfile.dev .

script:
  - docker run bhavyamarapa/radio-button-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-272412786920"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 
