sudo: required
services:
  - docker

before_install:
  - docker build -t bhavyamarapa/radio-button-app  -f Dockerfile.dev .

script:
  - docker run bhavyamarapa/radio-button-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "radio-button-app"
  env: " RadioButtonApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-272412786920"
  bucket_path: "radio-button-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
