sudo: required
services:
  - docker

before_install:
  - docker build -t bhavyamarapa/sample-radio-button  -f Dockerfile.dev .

script:
  - docker run bhavyamarapa/sample-radio-button npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Sample Radio Button"
  env: "SampleRadiobutton-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-272412786920"
  bucket_path: "Sample Radio Button"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 
